logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost/friends
    username: root
    password: $password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true